src/main/generated/com/twenty/inhub/boundedContext/category/QCategory.java, src/main/generated/com/twenty/inhub/boundedContext/question/entity/QQuestion.java, src/main/generated/com/twenty/inhub/boundedContext/question/entity/QTag.java, src/main/generated/com/twenty/inhub/boundedContext/underline/QUnderline.java, src/main/java/com/twenty/inhub/InhubApplication.java, src/main/java/com/twenty/inhub/boundedContext/category/Category.java, src/main/java/com/twenty/inhub/boundedContext/question/entity/Question.java, src/main/java/com/twenty/inhub/boundedContext/question/entity/QuestionType.java, src/main/java/com/twenty/inhub/boundedContext/question/entity/Tag.java, src/main/java/com/twenty/inhub/boundedContext/underline/Underline.java, src/main/resources/application.yml
Question,
Tag, 
Underline, 
Category Entity, 필드 생성  완료했습니다.
<br>
아직 push 되지 않은 객체에 대한 연관관계 선언은 주석처리했습니다.
=> feat: Question, Tag, Underline, Category Entity 필드 생성  완료

src/main/java/com/twenty/inhub/boundedContext/Answer/entity/Answer.java
- 만들어둔 것들과 Answer 필드 연결하고 생성했습니다.
=> feat : Answer 필드 생성

src/main/java/com/twenty/inhub/boundedContext/Answer/entity/Answer.java
=> chore : Answer Entity annotation 추가

.gitignore, src/main/java/com/twenty/inhub/boundedContext/Answer/controller/AnswerController.java, src/main/java/com/twenty/inhub/boundedContext/Answer/entity/Answer.java, src/main/java/com/twenty/inhub/boundedContext/Answer/repository/AnswerQueryRepository.java, src/main/java/com/twenty/inhub/boundedContext/Answer/repository/AnswerRepository.java, src/main/java/com/twenty/inhub/boundedContext/Answer/service/AnswerService.java
- AnswerService의 기초적인 것들을 추가했습니다.
- 답 생성
- 답 찾기
- 답 체크
- 답 수정
- 답 삭제
=> feat : AnswerService 추가 및 병합 충돌 수정

src/main/generated/com/twenty/inhub/boundedContext/question/entity/QChoice.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/QuestionController.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/QuestionFindController.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/form/CreateAnswerForm.java, src/main/java/com/twenty/inhub/boundedContext/question/entity/Choice.java, src/main/java/com/twenty/inhub/boundedContext/question/service/QuestionService.java, src/main/resources/templates/usr/question/fragment/play/card.html, src/main/resources/templates/usr/question/fragment/play/content.html, src/main/resources/templates/usr/question/fragment/play/nav.html, src/main/resources/templates/usr/question/fragment/play/stack.html, src/main/resources/templates/usr/question/fragment/play/valid.html, src/main/resources/templates/usr/question/top/play.html
- 랜덤문제 페이지에서 다음페이지를 누르면 입력한 정답이 저장되는 엔드포인트로 요청 보내는 기능을 구현했습니다.
=> feat: 랜덤문제에서 입력한 정답 요청하는 로직 구현 완료

src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/QuestionRestController.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/dto/QuestionReqDto.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/dto/QuestionResDto.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/dto/UpdateListReqDto.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/dto/UpdateListResDto.java, src/main/java/com/twenty/inhub/boundedContext/question/entity/Question.java, src/main/java/com/twenty/inhub/boundedContext/question/service/QuestionService.java, src/test/java/com/twenty/inhub/boundedContext/question/service/QuestionServiceTest.java
```yaml
"categoryId": 7,
"ReqDtoList": [
{
"question": 
"keyWord1": 
"keyWord2": 
"keyWord3": 
"keyWord4": 
"keyWord5": 
"keyWord6": 
},
}
]
```
테스트 해보고 이상없으면 update 로 ddl 옵션 변경하겠습니다.
=> feat: 질문 답변 대량등록 메서드 구현

src/main/java/com/twenty/inhub/boundedContext/member/service/MemberService.java, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/test/resources/application.yml
- storage
- 로컬 환경 -> local
- 운영 환경 -> profileImages
=> chore: s3 저장 로컬, 배포 환경 분리

src/main/java/com/twenty/inhub/base/security/CustomOAuth2UserService.java, src/main/java/com/twenty/inhub/base/security/OAuthAttributes.java, src/main/java/com/twenty/inhub/boundedContext/member/service/MemberService.java, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/test/resources/application.yml
- OAuthAtrributes 클래스 내 불필요한 것들 정리
=> refactor: 신규 회원가입 시 기본 닉네임 설정

src/main/java/com/twenty/inhub/boundedContext/category/Category.java, src/main/java/com/twenty/inhub/boundedContext/category/CategoryService.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/QuestionRestController.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/dto/CategoryReqDto.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/dto/UpdateCategoryDto.java
- 카테고리 대량등록 api 생성
- api end point 수정
=> test: 대량등록 테스트 완료

build.gradle, src/main/resources/application.yml
- prometheus 와 grafana setting 하겠습니다.
=> feat: monitering setting

src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/QuestionController.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/form/UpdateQuestionForm.java, src/main/java/com/twenty/inhub/boundedContext/underline/UnderlineController.java, src/main/resources/templates/usr/home/fragment/index/note.html, src/main/resources/templates/usr/home/fragment/index/play.html
- 메인페이지 샘플 컨텐츠 작동되도록 수정했습니다.
- 광고는 아직 작동 안됩니다.
- 배포환경에서 태그가 없을 때 수정이 안되던 문제 수정했습니다.
=> design: 메인페이지 컨탠츠 업데이트

Dockerfile
- 배포서버의 Shell script 에 타임존 설정하는 환경변수 추가했습니다.
=> fix: 타임존 문제 해결

src/main/generated/com/twenty/inhub/boundedContext/book/entity/QBook.java, src/main/java/com/twenty/inhub/boundedContext/book/controller/BookController.java, src/main/java/com/twenty/inhub/boundedContext/book/controller/form/BookCreateForm.java, src/main/java/com/twenty/inhub/boundedContext/book/entity/Book.java, src/main/java/com/twenty/inhub/boundedContext/book/repository/BookRepository.java, src/main/java/com/twenty/inhub/boundedContext/book/service/BookService.java, src/main/java/com/twenty/inhub/boundedContext/underline/Underline.java, src/main/java/com/twenty/inhub/boundedContext/underline/dto/UnderlineCreateForm.java, src/main/resources/templates/usr/question/fragment/detail/underline.html, src/test/java/com/twenty/inhub/boundedContext/book/service/BookServiceTest.java
- 문제집 기능을 하는 book entity 생성했습니다.
- create, find by id 구현 / 테스트 했습니다.
- create 엔드포인트 구현했습니다.
=> feat: book create, find by id 구현 / test / end point 완료

build.gradle, src/main/java/com/twenty/inhub/boundedContext/markdown/MarkdownComponent.java, src/main/java/com/twenty/inhub/boundedContext/post/controller/PostController.java, src/main/java/com/twenty/inhub/boundedContext/post/service/PostService.java, src/main/resources/templates/usr/post/create.html, src/main/resources/templates/usr/post/edit.html, src/main/resources/templates/usr/post/view.html
- 게시글 작성시 마크다운을 사용할 수 있도록 했습니다
- 글 작성후 수정 하려고 들어가면 마크다운 문법이 아닌 html태그가 보이는 문제가 있습니다
=> feat: 게시글에 마크다운 적용

src/main/java/com/twenty/inhub/boundedContext/chat/controller/ChatRoomController.java, src/main/java/com/twenty/inhub/boundedContext/chat/repository/ChatRoomRepository.java, src/main/java/com/twenty/inhub/boundedContext/chat/service/ChatRoomService.java, src/main/java/com/twenty/inhub/boundedContext/member/controller/MemberDto.java, src/main/resources/static/app.js, src/main/resources/static/common/common.css, src/main/resources/templates/usr/chat/room.html, src/main/resources/templates/usr/chat/rooms.html
- 관리자는 모든 채팅방을 확인할 수 있음
- 일반 유저는 자신의 문의 채팅만 확인 가능
=> refactor: 관리자 문의 채팅 로직 작업 및 디자인

src/main/java/com/twenty/inhub/base/appConfig/WebSocketConfig.java, src/main/java/com/twenty/inhub/boundedContext/member/controller/MemberController.java, src/main/resources/application-prod.yml, src/main/resources/templates/usr/member/changePw.html, src/main/resources/templates/usr/member/comment.html, src/main/resources/templates/usr/member/correct.html, src/main/resources/templates/usr/member/incorrect.html, src/main/resources/templates/usr/member/question.html
- 비밀번호 찾기 및 변경 에러 수정
- 배포 환경에서 소켓 연결이 안되는 오류 수정
- 배포 환경 ddl-auto 옵션 create로 수정
=> fix: 각종 에러 및 디자인 수정

src/main/java/com/twenty/inhub/base/appConfig/WebSocketConfig.java, src/main/java/com/twenty/inhub/boundedContext/member/controller/MemberController.java, src/main/resources/application-prod.yml, src/main/resources/templates/usr/member/changePw.html, src/main/resources/templates/usr/member/comment.html, src/main/resources/templates/usr/member/correct.html, src/main/resources/templates/usr/member/incorrect.html, src/main/resources/templates/usr/member/question.html
* fix: 비밀번호 찾기 및 변경 에러 수정
* design: 디자인 수정
* fix: 배포 환경에서 소켓 연결이 안되는 오류
* fix: 배포서버 ddl 옵션 create 변경
=> fix: 각종 에러 및 디자인 수정 (#152)

src/main/generated/com/twenty/inhub/boundedContext/device/QDevice.java, src/main/generated/com/twenty/inhub/boundedContext/member/entity/QMember.java, src/main/java/com/twenty/inhub/base/appConfig/WebMvcConfig.java, src/main/java/com/twenty/inhub/base/initData/InitData.java, src/main/java/com/twenty/inhub/base/interceptor/DeviceCheckInterceptor.java, src/main/java/com/twenty/inhub/boundedContext/device/Device.java, src/main/java/com/twenty/inhub/boundedContext/device/DeviceController.java, src/main/java/com/twenty/inhub/boundedContext/device/DeviceRepository.java, src/main/java/com/twenty/inhub/boundedContext/device/DeviceService.java, src/main/java/com/twenty/inhub/boundedContext/mail/service/MailService.java, src/main/java/com/twenty/inhub/boundedContext/member/entity/Member.java, src/main/java/com/twenty/inhub/boundedContext/note/controller/NoteController.java, src/main/java/com/twenty/inhub/boundedContext/note/service/NoteService.java, src/main/resources/templates/usr/member/device/authentication.html, src/main/resources/templates/usr/member/update.html, src/test/java/com/twenty/inhub/boundedContext/member/service/MemberServiceTest.java, src/test/java/com/twenty/inhub/boundedContext/note/service/NoteServiceTest.java
- 계정이 기존에 접속하던 환경과 다른 환경 접속 시,  이메일 인증을 해서 기기를 등록 시켜야함
- 다른 환경 기준 : 웹 브라우저, PC, 모바일, OS -> ```User-Agent```
=> feat: 기기 체크 기능 구현

src/main/java/com/twenty/inhub/base/appConfig/AppConfig.java, src/main/java/com/twenty/inhub/base/appConfig/AsyncConfig.java, src/main/java/com/twenty/inhub/boundedContext/answer/controller/AnswerController.java, src/main/java/com/twenty/inhub/boundedContext/gpt/GptService.java, src/main/resources/templates/error/404.html, src/main/resources/templates/error/500.html, src/main/resources/templates/usr/answer/top/wait.html
- Gpt api 비동기 처리되게 구현완료했습니다.
- 비동기 처리하고 나서 쪽지로 링크를 보내줘서 결과확인하게 추가했습니다.
- 404,500 페이지 간단하게 나오게 추가했습니다.
=> refactor : 쪽지결과 날라가게 수정

src/main/java/com/twenty/inhub/boundedContext/answer/controller/AnswerController.java, src/main/java/com/twenty/inhub/boundedContext/gpt/GptService.java, src/main/resources/templates/usr/answer/fragment/comments/comment.html
- 다른사람답변은 정답처리된거만 보이게 수정했습니다.
- 그 외는 객관식이 섞인경우 null값을 넣음으로서 번호가 밀리는 걸 수정했습니다.
=> refactor : 다른사람답변은 정답처리된거만 보이게수정

src/main/java/com/twenty/inhub/base/security/SecurityConfig.java, src/main/java/com/twenty/inhub/boundedContext/book/entity/Book.java, src/main/java/com/twenty/inhub/boundedContext/book/service/BookService.java, src/main/java/com/twenty/inhub/boundedContext/question/entity/Question.java, src/main/java/com/twenty/inhub/boundedContext/question/service/QuestionService.java, src/main/resources/templates/usr/search/fragment/question/content.html, src/main/resources/templates/usr/underline/fragment/book/table.html
- 문제 풀고 제출시 이벤트 작동 안되는 문제 해결
- 텍스트가 길어서 ui 가 깨지는 문제 해결
- cors 비활성화 헤제
- kako add fit 도입
=> fix: 문제 해결 후 난이도, 문제집 도전자 업데이트 안되는 문제 해결

src/main/generated/com/twenty/inhub/boundedContext/book/entity/QBook.java, src/main/generated/com/twenty/inhub/boundedContext/likeBook/QLikeBook.java, src/main/generated/com/twenty/inhub/boundedContext/member/entity/QMember.java, src/main/java/com/twenty/inhub/base/excption/ErrorResponse.java, src/main/java/com/twenty/inhub/base/excption/ExceptionController.java, src/main/java/com/twenty/inhub/base/excption/InvalidTokenException.java, src/main/java/com/twenty/inhub/base/excption/NotFoundException.java, src/main/java/com/twenty/inhub/boundedContext/book/controller/BookController.java, src/main/java/com/twenty/inhub/boundedContext/book/controller/BookRestOpenApiController.java, src/main/java/com/twenty/inhub/boundedContext/book/controller/SearchController.java, src/main/java/com/twenty/inhub/boundedContext/book/entity/Book.java, src/main/java/com/twenty/inhub/boundedContext/book/repository/BookQueryRepository.java, src/main/java/com/twenty/inhub/boundedContext/book/service/BookService.java, src/main/java/com/twenty/inhub/boundedContext/likeBook/LikeBook.java, src/main/java/com/twenty/inhub/boundedContext/likeBook/LikeBookRepository.java, src/main/java/com/twenty/inhub/boundedContext/likeBook/LikeBookService.java, src/main/java/com/twenty/inhub/boundedContext/member/entity/Member.java, src/main/java/com/twenty/inhub/boundedContext/question/controller/controller/QuestionOpenApiController.java, src/main/java/com/twenty/inhub/boundedContext/underline/UnderlineController.java, src/main/resources/templates/layout/top-navbar.html, src/main/resources/templates/usr/search/fragment/book/tab.html, src/main/resources/templates/usr/search/fragment/category/search.html, src/main/resources/templates/usr/search/fragment/member/content.html, src/main/resources/templates/usr/search/fragment/member/page.html, src/main/resources/templates/usr/search/fragment/member/search.html, src/main/resources/templates/usr/search/fragment/search/search.html, src/main/resources/templates/usr/search/top/member.html, src/main/resources/templates/usr/underline/fragment/book/title.html, src/main/resources/templates/usr/underline/top/book.html
- 문제집 좋아요 기능 구현
- member 검색 페이지 추가
- open api 용 exception handler 추가
=> feat: 문제집 좋아요 / member 찾기 / exception handler 구현

build.gradle, src/main/java/com/twenty/inhub/boundedContext/answer/controller/AnswerController.java
- 비동기처리시에 bookid가 없는 경우를 처음에 가정하지 않고 진행해서 발생한 오류
- book id 가 있는 경우와 없는 경우를 나눠서 진행으로 수정
=> fix : 그냥 문제풀때 문제집 때문에 쪽지안가던거 해결
